# Generated by Django 5.0 on 2023-12-20 21:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
    ]
